---
plugin: aws_ec2
aws_access_key: '<<your-access-key-here>>'
aws_secret_key: '<<your-secret-key-here>>'
strict: False
regions:
  - "us-east-2"
keyed_groups:
  - key: tags.Name
  - key: tags.user
filters:
 instance-state-name : running
